name: bedtools sort
description: >
  Sorts bed, vcf or gff files by chromosome and other criteria.
authors:
  - Antonie Vietor
input:
  - BED/GFF/VCF files
  - optional a tab separating file that determines the sorting order and contains the chromosome names in the first column
  - optional a fasta index file
output:
  - .sorted.bed or
  - .sorted.vcf or
  - .sorted.gff
