name: deepTools computeMatrix
description: >
  ``DeepTools``'s computeMatrix calculates scores per genome region and can be used as input for other tools or for the generation of a ``deepTools`` plotHeatmap or ``deepTools`` plotProfiles.
  For usage information about computeMatrix, please see  ``deepTools``'s `documentation <https://deeptools.readthedocs.io/en/develop/content/tools/computeMatrix.html>`_.
  For more information about ``deepTools``, also see the `source code <https://github.com/deeptools/deepTools>`_.

    +----------------------------+-------------------------------------+---------------------+-------------+
    | computeMatrix option       | Output format                       | Name of output      | Recommended |
    |                            |                                     |                     |             |
    |                            |                                     | variable to be used | extension   |
    +============================+=====================================+=====================+=============+
    | --outFileName, -out, -o    | gzipped matrix file                 | matrix_gz           | ".gz"       |
    +----------------------------+-------------------------------------+---------------------+-------------+
    | --outFileNameMatrix        | tab-separated table of matrix file  | matrix_tab          | ".tab"      |
    +----------------------------+-------------------------------------+---------------------+-------------+
    | --outFileSortedRegions     | BED matrix file with sorted regions | matrix_bed          | ".bed"      |
    |                            |                                     |                     |             |
    |                            | after skipping zeros or min/max     |                     |             |
    |                            |                                     |                     |             |
    |                            | threshold values                    |                     |             |
    +----------------------------+-------------------------------------+---------------------+-------------+

authors:
  - Antonie Vietor
input:
  - BED or GTF files (.bed or .gtf) AND
  - bigWig files (.bw)
output:
  - gzipped matrix file (.gz) AND/OR
  - tab-separated table of matrix file (.tab) AND/OR
  - BED matrix file with sorted regions after skiping zeros or min/max threshold values (.bed)
