name: picard CollectMultipleMetrics
description: >
  A ``picard`` meta-metrics tool that collects multiple classes of metrics.
  For usage information about CollectMultipleMetrics, please see  ``picard``'s `documentation <https://gatk.broadinstitute.org/hc/en-us/articles/360036510492-CollectMultipleMetrics-Picard>`_.
  For more information about ``picard``, also see the `source code <https://github.com/broadinstitute/picard>`_.
authors:
  - Antonie Vietor
input:
  - BAM file (.bam)
  - FASTA reference sequence file (.fasta or .fa)
output:
  - multiple metrics text files (_metrics) AND
  - multiple metrics pdf files (.pdf)
