name: bedtools complement
description: >
  ``Bedtools complement`` maps all regions of the genome which are not covered by the input.
authors:
  - Antonie Vietor
input:
  - BED/GFF/VCF files
  - genome file (`genome file format <https://bedtools.readthedocs.io/en/latest/content/general-usage.html#genome-file-format>`_)
output:
  - .bed.complement or
  - .vcf.complement or
  - .gff.complement