name: Release

on:
  release:
    types: [created]

jobs:
  publish-changelog:
    runs-on: ubuntu-latest
    steps:
      - name: generate changelog
        uses: ScottBrenner/generate-changelog-action@v1.1.1
        id: changelog
      - name: update release
        uses: tubone24/update_release@v1.0
        env:
          GITHUB_TOKEN: ${{ secrets.github_token }}
        with:
          body: |
            ${{ steps.Changelog.outputs.changelog }}
